language: go
os:
  - linux
go:
  - 1.10
  - tip
sudo: false
install:
  - mkdir -p $HOME/gopath/src/gopkg.in/hlandau/
  - ln -s $TRAVIS_BUILD_DIR $HOME/gopath/src/github.com/rai-project/passlib
  - cd $HOME/gopath/src/github.com/rai-project/passlib
  - go get
